### ISSUE TITLE
Linkedin

### ISSUE THREAD

**Issue by pablodelflores** [JuanjoSalvador/andalucia-developers#33]
¿Sería mala cosa añadir un campo más para que publiquemos nuestros Linkedin? Por no mezclarlos con web personal/Github.

Así podríamos crear sinergias laborales en dicha red social.

**Comment by JuanjoSalvador** [comment]
Pues... No veo por qué no.

**Comment by JuanjoSalvador** [comment]
He hecho un cambio, añadiendo la columna "Redes Sociales" para que podamos añadir Linkedin, Twitter, Mastodon, lo que queráis
